// lib/env/env.dart
import 'package:envied/envied.dart';

part 'env.g.dart';

/// **Env** is the class that will be generated by the build_runner command,
/// It will contain all the environment variables
@Envied(path: '.env')
abstract class Env {
  @EnviedField(varName: 'TMDB_KEY', obfuscate: true)
  static final tmdbApiKey = _Env.tmdbApiKey;
}
